ubuntubase:
    build: ./ubuntu-base
betools:
    build: ./betools
    expose:
        - "3000"
    volumes:
        - ./logs/:/var/log/betools/
	- ./betools/:/var/www/html/
    links:
        - mongodb:db
mongodb:
    build: ./mongodb
    expose:
        - "3333"
    volumes:
        - ./logs/:/var/log/mongodb/
        - ./mongodb/db:/data/db
nginxreverseproxy:
    build: ./nginx-reverse-proxy
    expose:
        - "80"
        - "443"
    links:
        - betools:app
    ports:
        - "80:80"
    volumes:
        - ./logs/:/var/log/nginx/
